"""Add Certificate model

Revision ID: 23560d1589a8
Revises: 0bd26526846f
Create Date: 2025-09-03 18:52:44.804476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23560d1589a8'
down_revision = '0bd26526846f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('issuing_organization', sa.String(length=150), nullable=False),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_timestamp'))

    op.drop_table('certificate')
    # ### end Alembic commands ###
