"""Add CreativeWork model

Revision ID: 45b85bdccc7a
Revises: 9d6a0866db84
Create Date: 2025-09-03 18:12:16.748032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b85bdccc7a'
down_revision = '9d6a0866db84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_work_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_work_timestamp'))

    op.drop_table('creative_work')
    # ### end Alembic commands ###
