"""add saved posts feature

Revision ID: 895661920f70
Revises: 9d6a0866db84
Create Date: 2025-09-03 17:32:37.158740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895661920f70'
down_revision = '9d6a0866db84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_posts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_posts')
    # ### end Alembic commands ###
