"""Add has_seen_welcome to User model

Revision ID: 9037740bf8ec
Revises: 90fcb1cb8051
Create Date: 2025-09-03 10:26:19.827396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9037740bf8ec'
down_revision = '90fcb1cb8051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seen_welcome', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_seen_welcome')

    # ### end Alembic commands ###
