"""add media model and update post model

Revision ID: d17147c01232
Revises: 9d9550477e9e
Create Date: 2025-09-03 16:50:29.612480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17147c01232'
down_revision = '9d9550477e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
