"""Remove has_seen_welcome from User model

Revision ID: f14e20df9e4a
Revises: 9d6a0866db84
Create Date: 2025-09-04 07:05:56.918449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14e20df9e4a'
down_revision = '9d6a0866db84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_seen_welcome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seen_welcome', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
